### ISSUE TITLE
Batch request is not working. (Library version: 1.1.1)

### ISSUE THREAD

**Issue by Vivaswan13** [SAP/olingo-jpa-processor-v4#232]
I tried to perform a batch request but gives an error saying 
---------
> org.apache.tomcat.util.http.fileupload.MultipartStream$MalformedStreamException: Stream ended unexpectedly
	at org.apache.tomcat.util.http.fileupload.MultipartStream.readHeaders(MultipartStream.java:520) ~[tomcat-embed-core-9.0.79.jar:9.0.79]
	at org.apache.tomcat.util.http.fileupload.impl.FileItemIteratorImpl.findNextItem(FileItemIteratorImpl.java:243) ~[tomcat-embed-core-9.0.79.jar:9.0.79]
	at org.apache.tomcat.util.http.fileupload.impl.FileItemIteratorImpl.<init>(FileItemIteratorImpl.java:142) ~[tomcat-embed-core-9.0.79.jar:9.0.79]
	at org.apache.tomcat.util.http.fileupload.FileUploadBase.getItemIterator(FileUploadBase.java:277) ~[tomcat-embed-core-9.0.79.jar:9.0.79]
	at org.apache.tomcat.util.http.fileupload.FileUploadBase.parseRequest(FileUploadBase.java:301) ~[tomcat-embed-core-9.0.79.jar:9.0.79]
	at org.apache.catalina.connector.Request.parseParts(Request.java:2850) ~[tomcat-embed-core-9.0.79.jar:9.0.79]
	at org.apache.catalina.connector.Request.getParts(Request.java:2751) ~[tomcat-embed-core-9.0.79.jar:9.0.79]
	at org.apache.catalina.connector.RequestFacade.getParts(RequestFacade.java:796) ~[tomcat-embed-core-9.0.79.jar:9.0.79]
	
-------------

The issue looks to be in Class "org.apache.olingo.server.core.deserializer.batch.BatchParser"  where returns an empty message list . 
com.sap.olingo.jpa.processor.core.api.JPAODataBatchProcessor #processBatch , is not able to deserialise input stream.
```
private List<List<Line>> splitBodyParts(final InputStream in, final String boundary) throws IOException,
      BatchDeserializerException {
    final BatchLineReader reader = new BatchLineReader(in);
    **final List<Line> message = reader.toLineList();**
    reader.close();
   return BatchParserCommon.splitMessageByBoundary(message, boundary);
  }
```
Here is version of pom. 
<odata.version>4.9.0</odata.version>
<dependency>
		    <groupId>com.sap.olingo</groupId>
		    <artifactId>odata-jpa-metadata</artifactId>
		    <version>1.1.1</version>
</dependency>

The body is:
<img width="709" alt="Screenshot 2023-10-18 at 11 37 55 AM" src="https://github.com/SAP/olingo-jpa-processor-v4/assets/67734448/cbe6f70b-c5d4-4351-a087-507a0cc4b87f">

Which version do you advise with odata-jpa-metadata

**Comment by wog48** [comment]
Unfortunately I was not able to reproduce this problem. Furthermore, I did not reached _org.apache.tomcat.util.http.fileupload.MultipartStream.readHeaders_. So I'm not able to give more advice. 

In case you think that _org.apache.olingo.server.core.deserializer.batch.BatchParser_ has a problem please create an issue in the [Olingo Jira](https://issues.apache.org/jira/projects/OLINGO/issues/).

**Comment by Vivaswan13** [comment]
I am facing the same issue as mentioned above. I changed the version to 2.0.0 . But still the issue is coming.

**Comment by Vivaswan13** [comment]
The issue is fixed now.

**Comment by akaFood** [comment]
> The issue is fixed now.

how did you fix this error? I am seeing the same error and couldn't find a solution
