### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by AhmadRedha** [SAP/olingo-jpa-processor-v4#61]
java.lang.NoSuchMethodError: com.google.common.collect.Sets$SetView.iterator()Lcom/google/common/collect/UnmodifiableIterator;
	at org.reflections.Reflections.expandSuperTypes(Reflections.java:380)
	at org.reflections.Reflections.<init>(Reflections.java:126)
	at com.sap.olingo.jpa.metadata.core.edm.mapper.impl.IntermediateServiceDocument.createReflections(IntermediateServiceDocument.java:263)
<hr>
java.lang.NoSuchMethodError: com.google.common.collect.Sets$SetView.iterator()Lcom/google/common/collect/UnmodifiableIterator;
	at org.reflections.Reflections.expandSuperTypes(Reflections.java:380)
	at org.reflections.Reflections.<init>(Reflections.java:126)
	at com.sap.olingo.jpa.metadata.core.edm.mapper.impl.IntermediateServiceDocument.createReflections(IntermediateServiceDocument.java:263)
	at com.sap.olingo.jpa.metadata.core.edm.mapper.impl.IntermediateServiceDocument.<init>(IntermediateServiceDocument.java:61)
	at com.sap.olingo.jpa.metadata.core.edm.mapper.impl.JPAServiceDocumentFactory.getServiceDocument(JPAServiceDocumentFactory.java:26)
	at com.sap.olingo.jpa.metadata.api.JPAEdmProvider.<init>(JPAEdmProvider.java:45)
	at tv.samim.iptv.yourPackage.common.OdataServlet.service(OdataServlet.java:49)

<hr>

```java
    ServletContext context = getServletContext();
            WebApplicationContext ctx =
                    WebApplicationContextUtils
                            .getWebApplicationContext(context);
            EntityManagerFactory emf = ctx.getBean("entityManagerFactory", EntityManagerFactory.class);

           // EntityManagerFactory myBean = (EntityManagerFactory) req.getSession().getAttribute("");
           // EntityManagerFactory emf = JPAEntityManagerFactory.getEntityManagerFactory(PUNIT_NAME, new HashMap<String, Object>());
            JPAEdmProvider metadataProvider = new JPAEdmProvider(PUNIT_NAME, emf, null, new String[]{"test"});
            OData odata = OData.newInstance();
```

**Comment by wog48** [comment]
It turned out that this is very likely a problem with `Guava` dependency and does not belong to jpa processor directly. 
JPA Processor uses [Reflections API](https://github.com/ronmamo/reflections), which uses  `Guava` v20.0. Please check if you have an older  `Guava`  version in you classpath/dependencies. 
See also:
[reflections issue #219](https://github.com/ronmamo/reflections/issues/219)
[reflections issue #194](https://github.com/ronmamo/reflections/issues/194)

**Comment by wog48** [comment]
I assume the problem has been solved. Otherwise reopen the issue.
